version: "3.9"
services:

  # mongodb single instance replica set 
  # multi instance replica set https://37yonub.ru/articles/mongo-replica-set-docker-localhost
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27018:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  
  #mongo2:
  #  image: mongo
  #  container_name: mongo2
  #  ports:
  #    - 27019:27017
  #  entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  
  #mongo3:
  #  image: mongo
  #  container_name: mongo2
  #  ports:
  #    - 27020:27017
  #  entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ] 
  
  mongosetup:
    image: mongo
    container_name: mongosetup
    depends_on:
      - mongo
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 10 && mongo --host mongo:27017 --eval 'rs.initiate()'"]  
  
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["postgres", "-c", "log_statement=all"]

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
      
  redis:
    container_name: redis
    image: redis
    ports:
     - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes