{{- define "shared.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-env
  labels: 
    {{- include "helm.labels" . | nindent 4 }}
data:
{{- toYaml .Values.env | nindent 2 }}
{{- end }}