{{- include "shared.ingress" . }}
---
{{- include "shared.service" . }}
---
{{- include "shared.deployment" . }}
---
{{- include "shared.serviceaccount" . }}
---
{{- include "shared.configmap" . }}
---
{{- include "shared.hpa" . }}